# Generated by Django 4.1 on 2022-10-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='military_time',
            field=models.BooleanField(default=False, help_text='Whether the user has enabled military time format'),
        ),
    ]
