# Generated by Django 4.1 on 2022-11-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='military_time',
            field=models.BooleanField(default=False, help_text='Whether the user prefers military time'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_notify',
            field=models.BooleanField(default=False, help_text='Whether the user should receive SMS'),
        ),
    ]
