# Generated by Django 4.1 on 2022-10-30 19:41
# Modified by Joseph Kolarik on 2022-11-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_military_time_user_sms_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
