# Generated by Django 4.1 on 2022-11-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_notify',
            field=models.BooleanField(default=False, help_text='Whether the user should receive SMS'),
        ),
        migrations.AlterField(
            model_name='user',
            name='military_time',
            field=models.BooleanField(default=False, help_text='Whether the user prefers military time'),
        ),
    ]
