# Generated by Django 3.1.2 on 2020-11-02 03:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('credit_hours', models.CharField(default='', max_length=10)),
            ],
            options={
                'ordering': ['subject_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notify', models.BooleanField(default=True)),
                ('email_unsub_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['lastname'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('short_title', models.CharField(help_text='E.g. ITEC', max_length=4, primary_key=True, serialize=False)),
                ('long_title', models.CharField(help_text='E.g. Information Technology', max_length=100)),
            ],
            options={
                'ordering': ['short_title'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('code', models.CharField(help_text='E.g. 202008', max_length=6, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='E.g. Fall 2020', max_length=20)),
                ('default', models.BooleanField(default=False, help_text='Whether this is the default term on the add-courses page')),
                ('update', models.BooleanField(default=True, help_text='Whether related sections and courses are updated')),
                ('display', models.BooleanField(default=True, help_text='Whether this term is displayed on the add-courses page')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('CRN', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('section_num', models.CharField(max_length=3)),
                ('section_title', models.CharField(blank=True, help_text="This is for classes with a section-specific title, e.g. if the course's title was 'Special Topics', the section's title could be '- Python for Data Analysis'", max_length=100)),
                ('credit_hours', models.SmallIntegerField()),
                ('days', models.CharField(blank=True, default='', max_length=7)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, default='', max_length=10)),
                ('enrolled', models.SmallIntegerField()),
                ('available', models.SmallIntegerField()),
                ('capacity', models.SmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
            ],
            options={
                'ordering': ['term_id', 'course', 'section_num'],
            },
        ),
    ]
