# Generated by Django 3.1.7 on 2021-04-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0002_suggestedschool'), ('core', '0003_suggestedschool_submitted'), ('core', '0004_auto_20210422_2255')]

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('edu_site', models.CharField(help_text="The school's main website, preferably with a .edu TLD.", max_length=100)),
                ('registration_site', models.CharField(help_text="The school's publicly accessible course registration page.", max_length=200)),
                ('notes', models.TextField(blank=True, help_text="Any additional information you'd like to add.", max_length=1000)),
                ('submitted', models.DateTimeField(auto_now_add=True, help_text='When the school suggestion was submitted.')),
            ],
            options={
                'ordering': ['school_name'],
            },
        ),
    ]
