# Generated by Django 3.1.2 on 2020-11-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201123_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['term', 'course', 'section_num']},
        ),
    ]
