# Generated by Django 3.1.2 on 2020-11-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201021_0239'),
        ('core', '0002_auto_20201102_0327'),
    ]

    operations = [
    ]
