# Generated by Django 3.1.5 on 2021-01-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201128_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_title',
            field=models.CharField(blank=True, help_text='For most sections, the section_title is equal to its course__title, however this is not the case for hybrid/online/special topics classes.', max_length=100),
        ),
    ]
