"""
Django settings for roster_sniper project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from roster_sniper.settings.base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Add development specific apps here
INSTALLED_APPS += [
    #'core.apps.RSConfig'
]

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

try:
    from .development_local import *
except:
    pass
