"""
Django settings for roster_sniper project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
from roster_sniper.settings.base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Add production specific apps here
INSTALLED_APPS += [
    #'django.contrib.staticfiles',
]

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'rsniper',
        'USER': 'rsniper',
        'PASSWORD': 'r0st3rsn1p3r',
        'HOST': 'localhost',
        'PORT': ''
    }
}
